// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/26/2025, 11:20:34 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/ERICA/OneDrive/Documents/project/ITE 123--18 - Copy/APps/nuxt-techstore/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ERICA/OneDrive/Documents/project/ITE 123--18 - Copy/APps/nuxt-techstore/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ERICA/OneDrive/Documents/project/ITE 123--18 - Copy/APps/nuxt-techstore/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ERICA/OneDrive/Documents/project/ITE 123--18 - Copy/APps/nuxt-techstore/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ERICA/OneDrive/Documents/project/ITE 123--18 - Copy/APps/nuxt-techstore/plugins/**/*.{js,ts,mjs}","C:/Users/ERICA/OneDrive/Documents/project/ITE 123--18 - Copy/APps/nuxt-techstore/composables/**/*.{js,ts,mjs}","C:/Users/ERICA/OneDrive/Documents/project/ITE 123--18 - Copy/APps/nuxt-techstore/utils/**/*.{js,ts,mjs}","C:/Users/ERICA/OneDrive/Documents/project/ITE 123--18 - Copy/APps/nuxt-techstore/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ERICA/OneDrive/Documents/project/ITE 123--18 - Copy/APps/nuxt-techstore/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ERICA/OneDrive/Documents/project/ITE 123--18 - Copy/APps/nuxt-techstore/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ERICA/OneDrive/Documents/project/ITE 123--18 - Copy/APps/nuxt-techstore/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;